"""Add refresh_tokens table

Revision ID: fd3df9809f73
Revises:
Create Date: 2025-12-20 12:39:54.470456

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fd3df9809f73"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
